### PR TITLE
5.201 Release

### PR DESCRIPTION
**Pull request by Pandrex247**
Awaiting propagation to Maven Central

### CODE REVIEW

**Comment by Pandrex247** [comment]
Built and pushed manually: https://hub.docker.com/repository/registry-1.docker.io/payara/server-full/tags?page=1

**Comment by poikilotherm** [comment]
If I provide a PR, would you mind switching the memory settings to use proper `UseContainerSupport` backported to Java 8 before creating a released tag?

**Comment by Pandrex247** [comment]
A 5.201 tag has already been created and pushed.
When you make your PR we can release it under the latest tag - Docker Hub might also actually build the other branches as we push to them I can't remember ottomh

**Comment by poikilotherm** [comment]
Thanks @Pandrex247 I created #118 as requested.

**Pull request merged**
