### PR TITLE
Proposed fix for https://github.com/payara/docker-payaraserver-full/issues/121

### PR DESCRIPTION
**Pull request by borisheithecker**

### CODE REVIEW

**Comment by OndroMih** [comment]
Can you please sign the Contributor License Agreement as described here: https://github.com/payara/Payara/blob/master/.github/CONTRIBUTING.md#legal-bits? I know you suggest a very small change but we need it to accept your pull request. If you think it's too much for such a small change, we can close this pull request and just fix #121 ourselves.

**Comment by rdebusscher** [comment]
Docker support is moved to the main Git repository.

**Comment by borisheithecker** [comment]
I've updated this because adding a newline with echo is somewhat inconsistent. Also, the newline shouldn't be added on very start of the container, only if deployment are really written to the file.

**Comment by borisheithecker** [comment]
I'm signing it, but I had to update the commit, as I've noticed that - though one line only - it shows some inconsistency.

**Comment by fturizo** [comment]
Closing this PR as this repository is to be archived and support for the Docker image is now on the main repository. If this PR is still applicable there, feel free to raise it in https://github.com/payara/Payara

**Pull request closed without merging**
